services:
  mssql2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    mem_limit: 3g
    restart: unless-stopped
    ports:
      - "15002:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Pwd2026Db"
      TZ: Asia/Shanghai
    user: root
    volumes:
      - mssql2022-data:/var/opt/mssql

volumes:
  mssql2022-data:
