services:
  h2:
    image: buildo/h2database:2020-12-11
    restart: unless-stopped
    networks:
      - dev_db_network
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2DATA=/h2-data
    volumes:
      - h2-data:/h2-data

networks:
  dev_db_network:
    external: true

volumes:
  h2-data:
