[kdcdefaults]
# 使用默认的 88 端口即可（容器间访问不需要端口映射，宿主机通过 docker 端口映射访问）
kdc_ports = 88
kdc_tcp_ports = 88
[realms]
TEST.COM = {
  # 数据库相关参数（必需）
  database_name = /var/lib/krb5kdc/principal
  key_stash_file = /etc/krb5kdc/stash

  #master_key_type = aes256-cts
  acl_file = /etc/krb5kdc/kadm5.acl
  dict_file = /usr/share/dict/words
  admin_keytab = /var/krb5kdc/kadm5.keytab
  max_renewable_life = 7d 0h 0m 0s
  default_principal_flags = +preauth
  # 仅使用 aes128，避免 AES256 key 与 JCE/JAAS 不兼容导致
  # "Cannot find key of appropriate type to decrypt AP-REQ - AES256 ..." 问题。
  supported_enctypes = aes128-cts:normal
}

