HiveZooKeeperClient {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/opt/hive/conf/hive.keytab"
  principal="hive/hadoop@TEST.COM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/opt/hive/conf/hive.keytab"
  principal="hive/hadoop@TEST.COM";
};


