services:
  pgvector:
    image: pgvector/pgvector:0.8.0-pg16
    container_name: pgvector
    hostname: pgvector
    ports:
      - "5433:5432"
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - dev_db_network
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      # - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
      - TZ=Asia/Shanghai
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  dev_db_network:
    external: true

volumes:
  pgvector_data:
