services:
  dm8:
    image: onlyoffice/damengdb:8.1.3
    privileged: true
    restart: unless-stopped
    ports:
      - "5236:5236"
    environment:
      - INSTANCE_NAME=dm8
      - PAGE_SIZE=16
      - LD_LIBRARY_PATH=/opt/dmdbms/bin
      - EXTENT_SIZE=32
      - BLANK_PAD_MODE=1
      - LOG_SIZE=1024
      - UNICODE_FLAG=1
      - LENGTH_IN_CHAR=1
    volumes:
      - dmdb_data:/opt/dmdbms/data

volumes:
  dmdb_data:
