services:
  gateway:
    image: nginx:1.25.3-alpine3.18
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - MY_VAR=${MY_VAR:-$(hostname)}
    # command: sh -c "echo MY_VAR is $BINARY_DOWNLOAD_VERSION"
    networks:
      - dev_db_network
      # - dev_sso_network
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl/
    restart: always

networks:
  dev_db_network:
    driver: bridge
    external: true
  # dev_sso_network:
  #   driver: bridge
  #   external: true
