user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    set_real_ip_from  10.0.0.0/8;   # Swarm 的内网 IP 段
    set_real_ip_from  192.168.0.0/16; # 如果你的 Docker 网络是 192 开头的
    # set_real_ip_from  127.0.0.1;   # 本机代理

    real_ip_header X-Forwarded-For;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

