services:
  vllm:
    image: vllm/vllm-openai:v0.10.1
    container_name: vllm-gpt-oss-20b
    ports:
      - "${VLLM_PORT}:8000"
    environment:
      - VLLM_USE_MODELSCOPE=${VLLM_USE_MODELSCOPE}
    volumes:
      - ${HOME}/.cache/modelscope:/root/.cache/modelscope
      # 手动模型路径, 会影响--model
      # - ./models:/root/models
    ipc: host
    command: >
      --trust-remote-code
      --tensor-parallel-size ${VLLM_TENSOR_PARALLEL_SIZE}
      --served-model-name ${VLLM_SERVED_MODEL_NAME}
      --model ${VLLM_MODEL}
      --max-model-len ${VLLM_MAX_MODEL_LEN}
      --gpu-memory-utilization ${VLLM_GPU_MEMORY_UTILIZATION}
      --max-num-batched-tokens ${VLLM_MAX_NUM_BATCHED_TOKENS}
      --max-num-seqs ${VLLM_MAX_NUM_SEQS}
      --swap-space ${VLLM_SWAP_SPACE}
