services:
  vault:
    image: hashicorp/vault:1.18.5
    ports:
      - "8200:8200"
    privileged: true
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_ADDR: http://127.0.0.1:8200
    restart: always
