Server {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/etc/security/keytabs/zookeeper.keytab"
  principal="zookeeper/zookeeper-zoo3-1.dev_db_network@TEST.COM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/etc/security/keytabs/zookeeper.keytab"
  principal="zookeeper/zookeeper-zoo3-1.dev_db_network@TEST.COM";
};


