Server {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/etc/security/keytabs/zookeeper.keytab"
  principal="zookeeper/zoo1.test.com@TEST.COM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  doNotPrompt=true
  useTicketCache=false
  keyTab="/etc/security/keytabs/zookeeper.keytab"
  principal="zookeeper/zoo1.test.com@TEST.COM";
};
