services:
  service:
    image: nginx:1.25.3-alpine3.18
    ports:
      - "80:80"
      - "443:443"
    # # network_mode: "host"
    networks:
      - dbserver
    #   - sso
    #   - file
    # - mqtt-server
    extra_hosts:
      - "HOST_DOMAIN:${NGINX_HOST_DOMAIN}"
    environment:
      - TZ=Asia/Shanghai
    secrets:
      - nginx_key
      - nginx_cert
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
        mode: 0444
      - source: nginx_sso.conf
        target: /etc/nginx/conf.d/sso.conf
        mode: 0444
      # - source: nginx_db.conf
      #   target: /etc/nginx/conf.d/db.conf
      #   mode: 0444
      # - source: nginx_test.conf
      #   target: /etc/nginx/conf.d/test.conf
      #   mode: 0444
      # - source: nginx_file.conf
      #   target: /etc/nginx/conf.d/file.conf
      #   mode: 0444
    volumes:
      - nginx_logs:/var/log/nginx
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
        reservations:
          memory: "256M"
      # endpoint_mode: dnsrr
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # logrotate:
  #   image: logrotate:1.0-alpine3.20
  #   command: ["sh", "-c", "logrotate -f /etc/logrotate.d/nginx"]
  #   volumes:
  #     - nginx_logs:/var/log/nginx
  #   deploy:
  #     mode: global
  #   configs:
  #     - source: logrotate-config
  #       target: /etc/logrotate.d/nginx
secrets:
  nginx_key:
    external: true
  nginx_cert:
    external: true
configs:
  # logrotate-config:
  #   external: true
  nginx.conf:
    external: true
  # nginx_test.conf:
  #   external: true
  nginx_sso.conf:
    external: true
  # nginx_db.conf:
  #   external: true
  # nginx_file.conf:
  #   external: true
  selfsigned.crt:
    external: true
  selfsigned.key:
    external: true

volumes:
  nginx_logs:
networks:
  dbserver:
    external: true
#   sso:
#     external: true
#   file:
#     external: true
# mqtt-server:
#   external: true
